### ISSUE TITLE
Error Import Module

### ISSUE THREAD

**Issue by eviling** [ing-bank/sparse_dot_topn#1]
Hi,

I am triying to import the package but I got the error: No module name
```
import numpy as np
from scipy.sparse import csr_matrix
import sparse_dot_topn.sparse_dot_topn as ct
```

> ModuleNotFoundError: No module named 'sparse_dot_topn'

Can you help me

**Comment by ymwdalex** [comment]
Hi Eveling, 

have you installed the package as readme said?

Zhe

**Comment by eviling** [comment]
thank you, it was that

**Comment by Adeinat** [comment]
No module named 'sparse_dot_topn' ?
