### ISSUE TITLE
Unable to install in windows

### ISSUE THREAD

**Issue by bihappywater** [ing-bank/sparse_dot_topn#10]
Hi, 
Thank you for sharing the package with us. I would like to use in windows system.
Got the error mesage: Microsoft Visual C++ 14.0 is required... where can I download the compiled file and how to install it without pip? Working in an environment can't using pip, and have to install manually... Sorry for silly question as a beginner in pydata.. 

Big thanks in advance!

**Comment by bihappywater** [comment]
Solved.  we need a wheel file and pip install .whl file.

**Comment by hsuthar1** [comment]
Hi - were you able to find a Windows whl file for this?  Trying to install on a non-networked PC and am running into an installation error too.

**Comment by Elfilali-Taoufiq** [comment]
hello,
where to find Whl file for windows plateform plz ?
