### ISSUE TITLE
BLD: Add support for Nanobind v2.0

### ISSUE THREAD

**Issue by RUrlus** [ing-bank/sparse_dot_topn#112]
### Describe your issue.

[Nanobind v2](https://nanobind.readthedocs.io/en/latest/changelog.html#version-2-0-0-may-23-2024) was recently released which removed support for `nb::raw_doc` which we use.

### Error message

```shell
‘raw_doc’ is not a member of ‘sdtn::bindings::nb’
```

**Comment by nhaunold** [comment]
@RUrlus hey - thank you for your work on this library! i ran into this problem recently installing some of our dependencies. right now i fixed it by pointing to your commit https://github.com/ing-bank/sparse_dot_topn/commit/7aba691036c53fe72e192c065e0b70e0659bee41 that restricts the nanobind version explicitly.

is it possible to cut a release including it? would love to have a built version of it on pip to avoid having to do the compile on CI.

**Comment by RUrlus** [comment]
Hi @nhaunold, good point! [Patch release v1.1.2](https://pypi.org/project/sparse-dot-topn/1.1.2/) is available on PyPi
