### ISSUE TITLE
ntop not working?

### ISSUE THREAD

**Issue by amine-plutoflume** [ing-bank/sparse_dot_topn#12]
Hello,
I am currently trying to evaluate this framework, but it seems to me that the `topn` argument is not used in the right way. For instance, whatever the value I put there, the number of results is always the same.
Could you please advise? 
Thanks a lot in advance.

**Comment by ymwdalex** [comment]
@amine-plutoflume thanks for your interests of this package.

if matrix `a` has M row and matrix `b` has N columns, the result matrix `c` by calling `awesome_cossim_topn(a, b, 10, 0.01)` will give you M*N sparse matrix. `topn` argument means in matrix `c`, each row has `topn` non-zero element. These non-zero elements are the top results per row. Please notice that matrix c is sparse CSR format, the actualy memory space is M*10.

If you want to iterate each element, you can use c.nonzero() to retrieve the nonzero element indices.

Are you a clear now?
