### ISSUE TITLE
Segmentation fault on small matrices

### ISSUE THREAD

**Issue by remidomingues** [ing-bank/sparse_dot_topn#13]
Hello team,

Many thanks for your package. I'm getting a segfault on small matrices, is this something we can avoid with a few cheks?
Here is an example of code raising this error:
```
from scipy.sparse import rand
from sparse_dot_topn import awesome_cossim_topn
a = rand(10, 150, density=0.005, format='csr')
b = rand(5, 150, density=0.005, format='csr')
awesome_cossim_topn(a, b, ntop=6, lower_bound=0)
```

**Comment by remidomingues** [comment]
Apologies, a call to transpose() was missing. However, I believe this segfault could be avoided by raising an exception when a.shape[1] != b.shape[0].

The correct code is thus:
```
from scipy.sparse import rand
from sparse_dot_topn import awesome_cossim_topn
a = rand(10, 150, density=0.005, format='csr')
b = rand(150, 5, density=0.005, format='csr')
awesome_cossim_topn(a, b, ntop=6, lower_bound=0)
```

**Comment by ymwdalex** [comment]
@remidomingues  thanks for your suggestion. I just created a PR, could you please review it? 
https://github.com/ing-bank/sparse_dot_topn/pull/23
Thanks!

**Comment by ymwdalex** [comment]
Merged in the master branch
