### ISSUE TITLE
Invalid numpy import in setup.py

### ISSUE THREAD

**Issue by remidomingues** [ing-bank/sparse_dot_topn#15]
Hello team,

We've been trying to package your lib in a Docker image, with our code, but we are facing an issue with the installation of the requirements based on `setup.py`.

Currently, `numpy` is imported at the beginning of `setup.py`, which means the installation fails if numpy is not installed before installing this library. Most of the time, a work around would be to install numpy, and then to restart the install of `sparse_dot_topn`. However, that doesn't work when you need to install all your requirements at once, e.g. with a `pip install -r requirements.txt`.

**Comment by aerdem4** [comment]
Sorry for the delay, we are looking for a clean and convenient solution for that. Did you find a workaround for yourself in the meantime?

**Comment by remidomingues** [comment]
Hello,
Changing the docker file works as a work-around, i.e. numpy can either be installed beforehand, or all libs can be installed one after the other, e.g. with `cat requirements.txt | xargs -n 1 -L 1 pip install`.

However, such solution does not work if you wish to package your project without installing dependencies. We solved the problem on our side, but there are numerous other packages which found a solution to this problem. For example, the `setup.py` of `scipy` is clearly tackling the current issue, which they describe here:
https://github.com/scipy/scipy/blob/master/setup.py#L528

**Comment by ValerianThomas** [comment]
Hi @aerdem4,
is there any update on the installation issue with the package dependencies?

**Comment by ymwdalex** [comment]
@ValerianThomas @remidomingues I update this package to 0.2.7, now it solved this issue :)

I will close this issue. If there is any problem about it, please let me know, thanks!
