### ISSUE TITLE
TypeError: awesome_cossim_topn() got an unexpected keyword argument 'use_threads'

### ISSUE THREAD

**Issue by maxkleiner** [ing-bank/sparse_dot_topn#16]
in the compare example
>>> c = awesome_cossim_topn(a, b, N, 0.01)
>>> d = awesome_cossim_topn(a, b, N, 0.01, use_threads=True, n_jobs=4)

**Comment by aerdem4** [comment]
@maxkleiner can you check your sparse_dot_topn version? Probably you are using an older version.

**Comment by ymwdalex** [comment]
@maxkleiner does it work properly?

**Comment by maxkleiner** [comment]
Works fine now, thanks!
