### ISSUE TITLE
dtype mismatch error

### ISSUE THREAD

**Issue by georgejosephada** [ing-bank/sparse_dot_topn#17]
Got a CountVectorizer csr matrix and trying to get cosine similarity using awesome_cossim_topn but it returns:
`matches = awesome_cossim_topn(tfidf_matrix, tfidf_matrix.transpose(), 10, 0.8, use_threads=True, n_jobs=-2)`

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-44-bf4fe3e852b5> in <module>
> ----> 1 matches = awesome_cossim_topn(tfidf_matrix, tfidf_matrix.transpose(), 10, 0.8, use_threads=True, n_jobs=-2)
> 
> ~\anaconda3\lib\site-packages\sparse_dot_topn\awesome_cossim_topn.py in awesome_cossim_topn(A, B, ntop, lower_bound, use_threads, n_jobs)
>      68             ntop,
>      69             lower_bound,
> ---> 70             indptr, indices, data, n_jobs)
>      71 
>      72     return csr_matrix((data,indices,indptr),shape=(M,N))
> 
> sparse_dot_topn/sparse_dot_topn_threaded.pyx in sparse_dot_topn.sparse_dot_topn_threaded.sparse_dot_topn_threaded()
> 
> ValueError: Buffer dtype mismatch, expected 'double' but got 'long long'

**Comment by aerdem4** [comment]
I guess we are missing a type check. Until we implement that, I have a workaround for you. Your CountVectorizer is probably creating a matrix of integers. This should solve the issue:
`tfidf_matrix = tfidf_matrix.astype(np.float32)`

**Comment by georgejosephada** [comment]
When I set the dtype of the input csr matrix to 

> np.float64 (np.float32 throws an error as well)

 then it works. Note that use_threads kills the jupyter lab kernel of mine if n_jobs is set below 0.
Getting the number of cores through:
```
import multiprocessing
n_jobs = multiprocessing.cpu_count() - 1
```
Works fine; awesome work :)

**Comment by cibic89** [comment]
if we are using vectorised data shouldn't uint8 or float16 be used instead?

**Comment by aerdem4** [comment]
Thanks!

I didn't exactly get why you want to set n_jobs to a negative value? Or is it just an accidental discovery that it kills your jupyter notebook?

Btw, be aware that you need to normalize the rows by yourself first, if you want to use it as cosine similarity. After normalization, you won't have integers probably anyway. awesome_cossim_topn is a bit misleading name, sorry for that. It only does the sparse_dot_topn part, therefore a normalization in advance is needed for cosine similarity.

**Comment by georgejosephada** [comment]
> I didn't exactly get why you want to set n_jobs to a negative value? Or is it just an accidental discovery that it kills your jupyter notebook?

In joblib parallelising we use n_jobs = -1 to use all cores and -2 to use all cores - 1

> Btw, be aware that you need to normalize the rows by yourself first, if you want to use it as cosine similarity. After normalization, you won't have integers probably anyway. awesome_cossim_topn is a bit misleading name, sorry for that. It only does the sparse_dot_topn part, therefore a normalization in advance is needed for cosine similarity.

Which is why you use tfidVectorizer right?

**Comment by aerdem4** [comment]
> In joblib parallelising we use n_jobs = -1 to use all cores and -2 to use all cores - 1

Now, I get it. Hopefully we will implement the same syntax. Thanks for the heads up.

> Which is why you use tfidVectorizer right?

TfidfVectorizer is not the reason because one may want to use IDF and it has nothing to do with it. But TF part makes sure that the norm of the vector is 1.

**Comment by georgejosephada** [comment]
> TfidfVectorizer is not the reason because one may want to use IDF and it has nothing to do with it. But TF part makes sure that the norm of the vector is 1.

One would use tf-idf to select the features used and normalise mainly. Why would you not use all features I wonder?

**Comment by ymwdalex** [comment]
@aerdem4 and @cibic89 thanks for the discussion. For now, I will add some explanation in the docstring to explain n_jobs, also raise a value error if n_jobs < 1

**Comment by ymwdalex** [comment]
@aerdem4  or @cibic89 , just create a PR, could you please review it? Thanks!
https://github.com/ing-bank/sparse_dot_topn/pull/20
