### ISSUE TITLE
Installing only works along with git

### ISSUE THREAD

**Issue by quantsegu** [ing-bank/sparse_dot_topn#2]
pip install git+https://github.com/ing-bank/sparse_dot_topn

command to be used for installing

**Comment by alysivji** [comment]
+1 to package this up and put on PyPI. Thanks.

**Comment by Lokdal** [comment]
I'd love to see this installed using pip as well, without needing git

**Comment by kfeaginsiii** [comment]
+1 on package this up. ended up here from => https://bergvca.github.io/2017/10/14/super-fast-string-matching.html  and can't seem to get this installed since I don't have git installed.

**Comment by phainom** [comment]
Availibility on Pypi would be nice indeed.

Thanks for your work!

**Comment by ymwdalex** [comment]
Thanks for your interests. I will start working on this soon.

**Comment by ymwdalex** [comment]
Now this package can be installed from pip directly. You need numpy and cython installed first!
`pip install sparse_dot_topn`

And I refactor the code, you can use this package easier. Please check the readme

```
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import rand
from sparse_dot_topn import awesome_cossim_topn

N = 10
a = rand(100, 1000000, density=0.005, format='csr')
b = rand(1000000, 200, density=0.005, format='csr')

c = awesome_cossim_topn(a, b, 5, 0.01)
```
