### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by YuxiangZheng** [ing-bank/sparse_dot_topn#21]
Collecting sparse_dot_topn
  Using cached https://files.pythonhosted.org/packages/69/49/6deae8f0500355a0a42d4181747721a10881aee4a757305024b89a9d760f/sparse_dot_topn-0.2.6.tar.gz
Building wheels for collected packages: sparse-dot-topn
  Building wheel for sparse-dot-topn (setup.py) ... [?25lerror
  ERROR: Command errored out with exit status 1:
   command: /anaconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-wheel-7l57wmrx --python-tag cp36
       cwd: /private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/
  Complete output (43 lines):
  /anaconda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn
  copying sparse_dot_topn/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn
  copying sparse_dot_topn/awesome_cossim_topn.py -> build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn
  running build_ext
  building 'sparse_dot_topn.sparse_dot_topn' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/sparse_dot_topn
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn.o -std=c++0x -pthread -O3
  In file included from ./sparse_dot_topn/sparse_dot_topn.cpp:640:
  In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
  /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  1 warning generated.
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_source.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_source.o -std=c++0x -pthread -O3
  g++ -bundle -undefined dynamic_lookup -L/anaconda/lib -L/anaconda/lib -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn.o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_source.o -L/anaconda/lib -o build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn/sparse_dot_topn.cpython-36m-darwin.so
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  building 'sparse_dot_topn.sparse_dot_topn_threaded' extension
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_threaded.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_threaded.o -std=c++0x -pthread -O3
  In file included from ./sparse_dot_topn/sparse_dot_topn_threaded.cpp:641:
  In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
  /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  1 warning generated.
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_source.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_source.o -std=c++0x -pthread -O3
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_parallel.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_parallel.o -std=c++0x -pthread -O3
  ./sparse_dot_topn/sparse_dot_topn_parallel.cpp:24:10: fatal error: 'thread' file not found
  #include <thread>
           ^~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for sparse-dot-topn
nning setup.py clean for sparse-dot-topn
Failed to build sparse-dot-topn
Installing collected packages: sparse-dot-topn
    Running setup.py install for sparse-dot-topn ... [?25lerror
    ERROR: Command errored out with exit status 1:
     command: /anaconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-record-unmqcd0l/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/
    Complete output (43 lines):
    /anaconda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn
    copying sparse_dot_topn/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn
    copying sparse_dot_topn/awesome_cossim_topn.py -> build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn
    running build_ext
    building 'sparse_dot_topn.sparse_dot_topn' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/sparse_dot_topn
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn.o -std=c++0x -pthread -O3
    In file included from ./sparse_dot_topn/sparse_dot_topn.cpp:640:
    In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
    /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    1 warning generated.
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_source.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_source.o -std=c++0x -pthread -O3
    g++ -bundle -undefined dynamic_lookup -L/anaconda/lib -L/anaconda/lib -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn.o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_source.o -L/anaconda/lib -o build/lib.macosx-10.7-x86_64-3.6/sparse_dot_topn/sparse_dot_topn.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    building 'sparse_dot_topn.sparse_dot_topn_threaded' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_threaded.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_threaded.o -std=c++0x -pthread -O3
    In file included from ./sparse_dot_topn/sparse_dot_topn_threaded.cpp:641:
    In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
    /anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    1 warning generated.
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_source.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_source.o -std=c++0x -pthread -O3
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/lib/python3.6/site-packages/numpy/core/include -I/anaconda/include/python3.6m -c ./sparse_dot_topn/sparse_dot_topn_parallel.cpp -o build/temp.macosx-10.7-x86_64-3.6/./sparse_dot_topn/sparse_dot_topn_parallel.o -std=c++0x -pthread -O3
    ./sparse_dot_topn/sparse_dot_topn_parallel.cpp:24:10: fatal error: 'thread' file not found
    #include <thread>
             ^~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /anaconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-install-o8ba7dss/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sp/0fzgff9x07g00xts17hwlrd80000gn/T/pip-record-unmqcd0l/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
[?25h

**Comment by ymwdalex** [comment]
@YuxiangZheng thanks for using this tool.

Could you please check if you can fix the issue by following @abeburnett suggestion in https://github.com/ing-bank/sparse_dot_topn/issues/7

> So far anyone else on a Mac who wanders across my issue, I seem to have resolved it by adding to my .bash_profile:
> 
> export CC=/usr/local/bin/gcc-8
> export CXX=/usr/local/bin/g++-8
> 
> And doing source ~/.bash_profile afterwards.

**Comment by kishoremarodia** [comment]
Getting same error on WINDOWS + Anaconda distribution. Tried using CONDA INSTALL as well, did not work. Any help please

**Comment by RainbowwwYQ** [comment]
The same for me... The interesting thing is that my friend can install it correctly... @_@

**Comment by ymwdalex** [comment]
@RainbowwwYQ @kishoremarodia @YuxiangZheng

Thanks for involving the discussion of this thread! We just released [v0.3.3](https://pypi.org/project/sparse-dot-topn/#files). We employed Github actions and CiBuildWheel, and make the wheels available for Py3.6-3.10 on multiple architectures of Linux, MacOS and Windows.

If you still have installation problems, please try the latest version with pip install.

If you find any problem with v0.3.3, please let us know. Thanks!
