### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by zhihongchensg** [ing-bank/sparse_dot_topn#26]
Hi, 

There seems to be an issue in the setup.py when i install. 

 if os.compiler['CC'] != 'mingw32':
    AttributeError: module 'os' has no attribute 'compiler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Would you kindly assist please.

thank you

**Comment by ymwdalex** [comment]
@zhihongchensg thanks for reporting this issue. I just push a quick fix with version 0.2.8. Could you please test it? Thanks!

**Comment by zhihongchensg** [comment]
Thanks for the quick fix. 

there is a 2nd error : 

 error: Microsoft Visual C++ 14.0 is required.  

Am not sure why because am using a higher version. 
And on https://visualstudio.microsoft.com/downloads/ - think i only see 13 and 15

full error appended below
================================

 Running setup.py install for sparse-dot-topn ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zh\\AppData\\Local\\Temp\\pip-install-bcoh_9vy\\sparse-dot-topn\\setup.py'"'"'; __file__='"'"'C:\\Users\\zh\\AppData\\Local\\Temp\\pip-install-bcoh_9vy\\sparse-dot-topn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zh\AppData\Local\Temp\pip-record-t7e26er_\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\zh\AppData\Local\Temp\pip-install-bcoh_9vy\sparse-dot-topn\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\sparse_dot_topn
    copying sparse_dot_topn\awesome_cossim_topn.py -> build\lib.win-amd64-3.7\sparse_dot_topn
    copying sparse_dot_topn\__init__.py -> build\lib.win-amd64-3.7\sparse_dot_topn
    running build_ext
    skipping './sparse_dot_topn\sparse_dot_topn.cpp' Cython extension (up-to-date)
    skipping './sparse_dot_topn\sparse_dot_topn_threaded.cpp' Cython extension (up-to-date)
    building 'sparse_dot_topn.sparse_dot_topn' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zh\\AppData\\Local\\Temp\\pip-install-bcoh_9vy\\sparse-dot-topn\\setup.py'"'"'; __file__='"'"'C:\\Users\\zh\\AppData\\Local\\Temp\\pip-install-bcoh_9vy\\sparse-dot-topn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zh\AppData\Local\Temp\pip-record-t7e26er_\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by zhihongchensg** [comment]
sorry,  i read your requirements and updated my packages. 

now there's a code error i think : 

lib\genericpath.py", line 30, in isfile
      st = os.stat(path)
  TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by ymwdalex** [comment]
@zhihongchensg thanks for the information.
- What is your OS environment and Python version?
- Does the disucssion and some solutions in this issue help? https://github.com/ing-bank/sparse_dot_topn/issues/4

**Comment by zhihongchensg** [comment]
yes it did. thank you
