### ISSUE TITLE
Dot product of sparse matrix

### ISSUE THREAD

**Issue by thiagoalencar** [ing-bank/sparse_dot_topn#30]
The matrix should not only be multiplied when the columns of row i is equal to columns of row j?
In your approach a column 0 of some row is multiplied by the column 1 another row.
 A.indptr = [0,2,4]
 A.indices=[0,4,0,1,1,2,3]
 A.data =[10,-2,3,9,7,8,7]
 
 B.indptr = [0,2,4]
 B.indices=[1,4,0,1,1,2,3]
 B.data =[5,-2,3,9,7,8,7]

In the first loop:
jj_start=0
jj_end=2
j=0
v=10
kk_start=0
kk_end=2
k = 1 //position of the Column of row 0 in matrix B is 1. Not 0
soma[k] = value of column 0 of matrix A * value of column 1 of Matrix B

This make sense?

**Comment by ymwdalex** [comment]
@thiagoalencar thanks for your question. 

array "sum" stores the dot products between the current row of matrix A and all columns of matrix B. for example, suppose we are in the loop of first row of A, sum[0] is A[0, :] multiply B[:, 0], and sum[1] is A[0, :] multiply B[:, 1].

In your example, B[0, 0] has value 0. k starts from 1. The element wise multiplication `sums[k] += v*Bx[kk]` only operates on non-zero element. It is a way to accelerate the sparse matrix mutilipcation.
