### ISSUE TITLE
cannot import name 'awesome_cossim_topn'

### ISSUE THREAD

**Issue by alejandrojcastaneira** [ing-bank/sparse_dot_topn#34]
Hello everyone,

After installing the package I'm trying to run the python example, however I'm getting this error:

from sparse_dot_topn import awesome_cossim_topn

> ImportError: cannot import name 'awesome_cossim_topn

Thanks you very much for the great work!

Best regards

**Comment by ymwdalex** [comment]
@alejandrojcastaneira  thanks for your feedback. Are you using Python 3 or Python 2? Are you installing by `pip install`?

**Comment by alejandrojcastaneira** [comment]
hello @ymwdalex yes, I am installing by `pip install sparse_dot_topn`  and using python 3.6.9.

**Comment by ymwdalex** [comment]
@alejandrojcastaneira Could you please try to upgrade your pip and see if it helps? `pip install -U pip`?

**Comment by alejandrojcastaneira** [comment]
I updated pip, both enviroment and system-wise however keeps showing the same message.

**Comment by ymwdalex** [comment]
@alejandrojcastaneira I tested in an online python 3.6 environment, and repeat the problem. 

I will setup a Python 3.6 environment and see what happens there. Thanks for reporting this problem!

**Comment by alejandrojcastaneira** [comment]
you are welcome @ymwdalex thank you for good work and super quick support!

**Comment by ymwdalex** [comment]
@alejandrojcastaneira I test it based in **a docker python 3.6.9 image**, and I couldn **not** repeat the problem.

Here is my dockerfile
```
FROM python:3.6.9-slim

ADD test.py /

RUN apt-get update \
    && apt-get install gcc g++ -y \
    && pip install --upgrade pip \
    && pip install sparse_dot_topn

CMD python test.py 
```

And test.py
```
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import rand
from sparse_dot_topn import awesome_cossim_topn

N = 10
a = rand(100, 100000, density=0.005, format='csr')
b = rand(100000, 200, density=0.005, format='csr')

# Use standard implementation
c = awesome_cossim_topn(a, b, N, 0.01)

# Use parallel implementation with 4 threads
d = awesome_cossim_topn(a, b, N, 0.01, use_threads=True, n_jobs=4)
```

Maybe upgrading your python environment to Python 3.7?

**Comment by alejandrojcastaneira** [comment]
hi @ymwdalex I made a newbie mistake, I named the python script were I was running the example with the exact name of the library, that's why I was getting the import error in python, please, sorry for the confusion.

Thanks you very much for your good work and your fast attention.
