### ISSUE TITLE
Will it work Windows with anaconda?

### ISSUE THREAD

**Issue by Sandy4321** [ing-bank/sparse_dot_topn#35]
Will it work Windows with anaconda?

**Comment by bballamudi** [comment]
I am able to install it on win10 using conda.

**Comment by Sandy4321** [comment]
What is about big data,did you compared with spark or GPU use
What is about gensim implementation?

**Comment by ymwdalex** [comment]
@Sandy4321 could you please use `conda install -c conda-forge sparse_dot_topn` to install?
