### ISSUE TITLE
Installation shows success but can not import module (improper installation)

### ISSUE THREAD

**Issue by shoanjain** [ing-bank/sparse_dot_topn#40]
EMR 5.29 on AWS, with Amazon Linux. Python 3.6

- When I run python3 -m pip install sparse-dot-topn in my terminal, I get the messaging saying  Successfully installed sparse-dot-topn. However, it is not being installed. (checked in the following ways)

- When I try to import the module, I get the ModuleNotFoundError

- I tried installing as below, I am able to import the module, but I can't import a specific function
```sudo python3 -m pip --verbose install git+https://github.com/ing-bank/sparse_dot_topn.git```

```
from sparse_dot_topn import awesome_cossim_topn
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'awesome_cossim_topn'
```
- When I try to uninstall, 
```
python3 -m pip --verbose uninstall sparse_dot_topn
WARNING: Skipping sparse-dot-topn as it is not installed
```

So even though I get successfully installed messaging, the module is clearly not being installed properly

Versions for related packages are as follows: (I upgrades pip and setuptools based on previous installation errors)
1. numpy (1.14.5) (I uninstalled numpy and the package installed this version as a part of it's dependency)
2. pip (20.2.2)
3. setuptools (50.0.3)

Could you help me with the correct installation?

**Comment by ymwdalex** [comment]
@shoanjain thanks for the feedback. Are you able to install by using the bootstrap action as this document describes? https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-jupyterhub-install-kernels-libs.html

BTW, numpy 1.14 has bug (https://github.com/scikit-image/scikit-image/issues/3655) and sparse_dot_topn couldn't run successfully with numpy 1.14. Please also upgrade numpy in the bootstrap action script.

**Comment by shoanjain** [comment]
Thanks for getting back to me on this issue. There was some issue with uninstalling numpy where I had to uninstall it more than once else the uninstallation was unsuccessful. After that when I install numpy, 1.19.2 gets installed properly and I am able to install this package as well
