### ISSUE TITLE
How to user other similarity method other than cosine

### ISSUE THREAD

**Issue by yinxiongchen** [ing-bank/sparse_dot_topn#41]
I am trying to calculate the similarity score other than consine. 
How should I modify it?

**Comment by ymwdalex** [comment]
@yinxiongchen thanks for your interests.

This package only support cosine similarity. If you want other metrics approximately similarity computation, you can check some package like https://github.com/spotify/annoy or https://github.com/facebookresearch/faiss

**Comment by Mikehem** [comment]
@ymwdalex where you able to measure the performance with respect to annoy and faiss?
