### ISSUE TITLE
cosine similarity

### ISSUE THREAD

**Issue by cvsekhar** [ing-bank/sparse_dot_topn#43]
I have a question, when using the norm of the vectors and comparing the results with cossim top n, it's giving different results.
Is it because this library does only dot product but not use the norm of the vectors? Should we normalize the vectors before calling this function?

**Comment by sarimak** [comment]
Yes, if you want to use cosine similarity for neighbors, you have to pre-normalize (L2 norm) the samples.

**Comment by cvsekhar** [comment]
Than you @sarimak just to confirm was normalizing for cosine similarity
