### ISSUE TITLE
Integer support

### ISSUE THREAD

**Issue by remidomingues** [ing-bank/sparse_dot_topn#44]
Hi team,

A great many thanks for this library.
The multithreaded and topn functionalities are just great to perform fast and low memory dot products with topn selection.

However, the current lib only supports float matrices. As we usually use count sparse matrices which fit in an np.int16, we end up casting our matrices in float in order to feed them to the library. Although this works well, we still end up wasting a lot of computation time which could be avoided if we were to perform only int multiplications.

Adding such functionality (e.g. with a dtype parameter to the awesome_cossim_topn function) would be amazing and would make this lib even faster.

Thanks!

**Comment by ymwdalex** [comment]
Hi @remidomingues , thanks for your feedback!

I checked the code, it is a doable but tedious task. I don't know how to make polymorphism cython code, so probably we need to create a new interface, and change the corresponding functions in python, cython and c++ files. 

I wonder how much performance improvement the integer support will bring in your case? I would like to evaluate the impact.

Thanks!

**Comment by remidomingues** [comment]
That's a very good question. I initially thought that moving from float to integer multiplications could save both computation time and memory usage, althought based on this thread, I'm no longer sure: https://stackoverflow.com/questions/2550281/floating-point-vs-integer-calculations-on-modern-hardware

I performed a few quick experiments which also suggest that the reported numbers are correct, i.e. that integer multiplications are slower than floating point multiplications.

Many thanks nonetheless for having considered it.
