### ISSUE TITLE
Installation error in ubuntu 18.04

### ISSUE THREAD

**Issue by Sooraj577** [ing-bank/sparse_dot_topn#45]
I tried installing using **pip install sparse_dot_topn** but the control is showing the below error.

Collecting sparse_dot_topn
  Using cached sparse_dot_topn-0.2.9.tar.gz (106 kB)
Requirement already satisfied: setuptools>=18.0 in /home/user/.virtualenvs/py38/lib/python3.8/site-packages (from sparse_dot_topn) (50.3.2)
Requirement already satisfied: cython>=0.29.15 in /home/user/.virtualenvs/py38/lib/python3.8/site-packages (from sparse_dot_topn) (0.29.21)
Requirement already satisfied: numpy>=1.16.6 in /home/user/.virtualenvs/py38/lib/python3.8/site-packages (from sparse_dot_topn) (1.18.5)
Requirement already satisfied: scipy>=1.2.3 in /home/user/.virtualenvs/py38/lib/python3.8/site-packages (from sparse_dot_topn) (1.4.1)
Building wheels for collected packages: sparse-dot-topn
  Building wheel for sparse-dot-topn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/.virtualenvs/py38/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ci104tth/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ci104tth/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qql7c8gr
       cwd: /tmp/pip-install-ci104tth/sparse-dot-topn/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/sparse_dot_topn
  copying sparse_dot_topn/__init__.py -> build/lib.linux-x86_64-3.8/sparse_dot_topn
  copying sparse_dot_topn/awesome_cossim_topn.py -> build/lib.linux-x86_64-3.8/sparse_dot_topn
  running build_ext
  skipping './sparse_dot_topn/sparse_dot_topn.cpp' Cython extension (up-to-date)
  skipping './sparse_dot_topn/sparse_dot_topn_threaded.cpp' Cython extension (up-to-date)
  building 'sparse_dot_topn.sparse_dot_topn' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/sparse_dot_topn
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -I/home/user/.virtualenvs/py38/include/python3.8 -I/home/user/.virtualenvs/py38/lib/python3.8/site-packages/numpy/core/include -c ./sparse_dot_topn/sparse_dot_topn.cpp -o build/temp.linux-x86_64-3.8/./sparse_dot_topn/sparse_dot_topn.o -std=c++0x -pthread -O3
  ./sparse_dot_topn/sparse_dot_topn.cpp:32:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for sparse-dot-topn
  Running setup.py clean for sparse-dot-topn
Failed to build sparse-dot-topn
Installing collected packages: sparse-dot-topn
    Running setup.py install for sparse-dot-topn ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/.virtualenvs/py38/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ci104tth/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ci104tth/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3yr89uhx/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.virtualenvs/py38/include/site/python3.8/sparse-dot-topn
         cwd: /tmp/pip-install-ci104tth/sparse-dot-topn/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/sparse_dot_topn
    copying sparse_dot_topn/__init__.py -> build/lib.linux-x86_64-3.8/sparse_dot_topn
    copying sparse_dot_topn/awesome_cossim_topn.py -> build/lib.linux-x86_64-3.8/sparse_dot_topn
    running build_ext
    skipping './sparse_dot_topn/sparse_dot_topn.cpp' Cython extension (up-to-date)
    skipping './sparse_dot_topn/sparse_dot_topn_threaded.cpp' Cython extension (up-to-date)
    building 'sparse_dot_topn.sparse_dot_topn' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/sparse_dot_topn
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -I/home/user/.virtualenvs/py38/include/python3.8 -I/home/user/.virtualenvs/py38/lib/python3.8/site-packages/numpy/core/include -c ./sparse_dot_topn/sparse_dot_topn.cpp -o build/temp.linux-x86_64-3.8/./sparse_dot_topn/sparse_dot_topn.o -std=c++0x -pthread -O3
    ./sparse_dot_topn/sparse_dot_topn.cpp:32:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/.virtualenvs/py38/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ci104tth/sparse-dot-topn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ci104tth/sparse-dot-topn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3yr89uhx/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.virtualenvs/py38/include/site/python3.8/sparse-dot-topn Check the logs for full command output.

I tried to install in a venv and using python 3.8, ubuntu 18.04.

**Comment by selfcontrol7** [comment]
Please, any updates? Same issue on CentOs 8.

**Comment by ymwdalex** [comment]
@selfcontrol7 @Sooraj577 

Thanks for the feedback! We just released [v0.3.3](https://pypi.org/project/sparse-dot-topn/#files). We employed Github actions and CiBuildWheel, and make the wheels available for Py3.6-3.10 on multiple architectures of Linux, MacOS and Windows.

If you still have installation problems, please try the latest version.

If you find any problem with v0.3.3, please let us know. Thanks!

**Comment by ymwdalex** [comment]
[v0.3.3](https://pypi.org/project/sparse-dot-topn/#files) should fix this issue
