### ISSUE TITLE
Out of bounds on buffer access (axis 0)

### ISSUE THREAD

**Issue by selfcontrol7** [ing-bank/sparse_dot_topn#49]
Hello, I have been using the library and worked perfectly with a couple of datasets I tried with. 
However, for some reasons I am still trying to understand, with certain datasets I got the following error: 

```
sparse_dot_topn/sparse_dot_topn.pyx in sparse_dot_topn.sparse_dot_topn.sparse_dot_topn()

sparse_dot_topn/sparse_dot_topn.pyx in sparse_dot_topn.sparse_dot_topn.sparse_dot_topn()

IndexError: Out of bounds on buffer access (axis 0)
```

Please, can you help me to understand what I did wrong and how I can fix it?

Thank you again.

**Comment by ymwdalex** [comment]
Could you please show me the dimension of your input sparse matrix?

**Comment by ejportillap** [comment]
Hi, i have the same issue and found the general reason, this happens when the result of the matrix multiplication is a zero matrix. 
to reproduce this issue you can create two matrix where the dot product is a zero matrix.

If i can help with anythong else, let me know. Thanks!

**Comment by ymwdalex** [comment]
Thanks @ejportillap  for your answer. 

@selfcontrol7 is your problem solved?

**Comment by selfcontrol7** [comment]
Thank you for your answer @ejportillap. I used another dataset that was probably giving a dot product different than zero, so the problem disappeared again. But now at least I know the reason.
Problem solved @ymwdalex .
