### ISSUE TITLE
Similarity scores not between 0 and 1

### ISSUE THREAD

**Issue by mayankkapoor123456** [ing-bank/sparse_dot_topn#5]
When computing the cosine similarity,  the similarity scores are not within the range 0 and 1.

import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import rand
from sparse_dot_topn import awesome_cossim_topn

N = 10
a = rand(100, 1000000, density=0.005, format='csr')
b = rand(1000000, 200, density=0.005, format='csr')

c = awesome_cossim_topn(a, b, 5, 0.01)

c.data
![image](https://user-images.githubusercontent.com/7789754/53252515-1ccb3180-36e5-11e9-8785-6322791d612c.png)

Shouldn't the above scores be between 0 and 1?

**Comment by aerdem4** [comment]
Actually function name awesome_cossim_topn is a bit misleading. What it does actually is sparse dot product and top n selection. In order to use it as a cosine similarity, you need to make sure that every row has unit norm before the multiplication.
