### ISSUE TITLE
Install without Microsoft Visual C++ Build Tools?

### ISSUE THREAD

**Issue by dbcandle** [ing-bank/sparse_dot_topn#50]
Is there a way to install (via pip) sparse_dot_topn without having Visual C++ Build Tools?  

I work in a large organization, and A) it is hard to get software installed and B)  the Visual C++ Build Tools license says it is only for use with various incarnations of Visual Studio.  I don't have Visual Studio, and the Community Edition can't be used in a large organization except in very limited cases which don't apply to me.

**Comment by dhiraj-das** [comment]
following

**Comment by ymwdalex** [comment]
@dhiraj-das @dbcandle 

Thanks for your feedback! We just released [v0.3.3](https://pypi.org/project/sparse-dot-topn/#files). We employed Github actions and CiBuildWheel, and make the wheels available for Py3.6-3.10 on multiple architectures of Linux, MacOS and Windows.

If you still have installation problems on windows OS, please try the latest version.

If you find any problem with v0.3.3, please let us know. Thanks!

**Comment by ymwdalex** [comment]
[v0.3.3](https://pypi.org/project/sparse-dot-topn/#files) should fix this issue
