### ISSUE TITLE
ImportError: cannot import name 'sparse_dot_topn' from 'sparse_dot_topn'

### ISSUE THREAD

**Issue by vidushi97** [ing-bank/sparse_dot_topn#54]
Hi! 
I am trying to install 'sparse_dot_topn' in my offline environment but it keeps giving me this error. I am using python 3.7.4 and pip 19.2.3. Please help! 

Thanks!

**Comment by ymwdalex** [comment]
@vidushi97 probably your current folder has `sparse_dot_topn` subfolder?
