### ISSUE TITLE
Error when import sparse_dot_topn.sparse_dot_topn - throw_bad_array_new_lengthv

### ISSUE THREAD

**Issue by Soufraz** [ing-bank/sparse_dot_topn#58]
Hi, I could install and make it work only with `conda install -c conda-forge sparse_dot_topn`.
But with venv I cant use the lib. I can install but I cant import the lib. What am I missing here?

```
import sparse_dot_topn.sparse_dot_topn
.local/lib/python3.8/site-packages/sparse_dot_topn/sparse_dot_topn.cpython-38-x86_64-linux-gnu.so: undefined symbol: 
_ZSt28__throw_bad_array_new_lengthv
```

Python 3.8.8
sparse-dot-topn==0.3.1

**Comment by ymwdalex** [comment]
@Soufraz thanks for reporting this issue. It feels related to CPU architecture, compiler and OS(?). Which CPU, OS and C++ compiler are you using?

@stephanecollot or @ParticularMiner do you have any clue of this issue?

**Comment by ParticularMiner** [comment]
Hi @Soufraz (@ymwdalex )

Just to be clear: 
After activating your virtual environment and executing the command: 

```bash
conda install -n [yourenvname] sparse_dot_topn
```
 the package does not install?  Or do you mean the package gets installed but does not work when it is run? 
 
Please provide more details.

**Comment by Soufraz** [comment]
@ymwdalex 
cpu
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    CPU family:          6
```

os
```
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.7
```

c++ compiler
`g++ (GCC) 11.1.0`

@ParticularMiner 
I cant make it work with venv. Only with conda and specifically with:
`conda install -c conda-forge sparse_dot_topn`
Without conda -c conda-forge it doesnt work.

Complete stacktrace:
```
File "/home/soufraz/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 6, in <module>
    from tfidf import get_tfidf_matrix, find_similars
  File "./tfidf.py", line 7, in <module>
    import sparse_dot_topn.sparse_dot_topn as ct  #Cosine Similarity
  File "/home/soufraz/Projects/my-project/env/lib/python3.8/site-packages/sparse_dot_topn/__init__.py", line 5, in <module>
    from sparse_dot_topn.awesome_cossim_topn import awesome_cossim_topn
  File "/home/soufraz/Projects/my-project/env/lib/python3.8/site-packages/sparse_dot_topn/awesome_cossim_topn.py", line 7, in <module>
    from sparse_dot_topn import sparse_dot_topn as ct
ImportError: /home/soufraz/Projects/my-project/env/lib/python3.8/site-packages/sparse_dot_topn/sparse_dot_topn.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

**Comment by ParticularMiner** [comment]
@Soufraz 

I use venv too and I encounter no problems, so I’m unable to reproduce your errors.  Can you please provide the exact sequence of commands that led to these error messages?

**Comment by Soufraz** [comment]
@ParticularMiner 

sequence
```
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
```

requirements.txt
```
fastapi==0.67.0
pandas==1.3.0
python-multipart==0.0.5
sklearn==0.0
sparse-dot-topn==0.3.1
Unidecode==1.2.0
uvicorn==0.14.0
scipy>=1.2.3
cython>=0.29.15
numpy>=1.16.6
```

Then after access the repl and type `import sparse_dot_topn.sparse_dot_topn` I get the error

Where python3 is Python 3.8.8

**Comment by Soufraz** [comment]
Now I realize that when installed with conda, those packages are installed together:
```
  libblas            conda-forge/linux-64::libblas-3.9.0-9_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-9_openblas
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-11.1.0-h69a702a_0
  libgfortran5       conda-forge/linux-64::libgfortran5-11.1.0-h6c583b3_0
  liblapack          conda-forge/linux-64::liblapack-3.9.0-9_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.15-pthreads_h8fe5266_1
  numpy              conda-forge/linux-64::numpy-1.21.1-py37h038b26d_0
  python_abi         conda-forge/linux-64::python_abi-3.7-2_cp37m
  scipy              conda-forge/linux-64::scipy-1.7.0-py37h29e03ee_1
  sparse_dot_topn    conda-forge/linux-64::sparse_dot_topn-0.3.1-py37h2527ec5_0
```
I think that this doesnt happen with venv.

**Comment by Soufraz** [comment]
I managed to work in venv! Exactly with this versions in requirements.txt:

sparse-dot-topn==0.3.1
scipy>=1.7.0
cython>=0.29.15
numpy>=1.21.1

Python version 3.9.5

I fixed the versions that was being installed from conda-forge repo.

Thank you!

**Comment by ParticularMiner** [comment]
@Soufraz 

Glad to hear it’s working!

**Comment by Soufraz** [comment]
It should work with python 3.7? The same steps but with python 3.7 doesnt works.

**Comment by ParticularMiner** [comment]
@Soufraz 
It should work with Python 3.7 (follow the [link](https://github.com/ing-bank/sparse_dot_topn/runs/2832135906?check_suite_focus=true) to see and examine our installation test logs).

**Comment by ymwdalex** [comment]
@ParticularMiner thanks a lot for tracing this issue!
