### ISSUE TITLE
parallelize the entire computation  

### ISSUE THREAD

**Issue by paritoshgupta** [ing-bank/sparse_dot_topn#6]
Is there any way I can leverage all the CPUs of my local system to parallelize the computations?

**Comment by aerdem4** [comment]
The algorithm is not multithreaded yet. For now, you can split the matrix A into chunks and keep the matrix B as it is, then use multiprocessing. (https://docs.python.org/3.6/library/multiprocessing.html)

**Comment by g-rutter** [comment]
#11

**Comment by ymwdalex** [comment]
@paritoshgupta  parallelization has been merge in v0.2.6
