### ISSUE TITLE
setup.py ln 10 :   Encoding='utf-8' problem on python 2.7x 

### ISSUE THREAD

**Issue by breardon2011** [ing-bank/sparse_dot_topn#8]
Hey so, I couldn't pip install on my local machine, but I could pip3 install. I noticed that the error I was getting was as follows: 

"ld-D0T7nh/setup.py", line 10, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/x/x/x

To fix this, I downloaded the repo, removed the encoding='utf-8' line on line 10. and then pip installed my edited package locally and it went without a hitch. 

Don't know if there is something else at play here but FYI.

**Comment by ymwdalex** [comment]
@breardon2011 I fixed the bug. Now this package should be installed on python2 correctly.

Thanks
