### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by silverbakk** [ing-bank/sparse_dot_topn#9]
I have recently tried to install this package and I have had a couple issues so far, one I was able to solve.

When installing in Python2.7 environment, I had to remove the encoding section from line 10 of the setup.py file. This allowed it to successfully install.

After this, I am unable to import the module from anywhere else besides the directory it is actually installed in (python2.7/dist-packages). Trying to narrow it down, it appears it is looking for another sparse_dot_topn directory (sparse_dot_topn/sparse_dot_topn) which is not created when using the setup.py file with pip.

`In [1]: import sparse_dot_topn
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d77e24a3bba9> in <module>()
----> 1 import sparse_dot_topn

/usr/local/lib/python2.7/dist-packages/sparse_dot_topn/__init__.py in <module>()
----> 1 from sparse_dot_topn.awesome_cossim_topn import awesome_cossim_topn

ImportError: No module named awesome_cossim_topn
`
Below is the package after the setup.py file is executed.

`user@server:/usr/local/lib/python2.7/dist-packages/sparse_dot_topn$ ls
awesome_cossim_topn.py  awesome_cossim_topn.pyc  __init__.py  __init__.pyc  sparse_dot_topn.so`

I am not sure exactly how to fix this, but would appreciate any help. Thanks.

**Comment by ymwdalex** [comment]
@SecJesus thanks for the message. I fixed the problem, make it python2 and python3 compatible. 

please try the latest version. Thanks!

**Comment by silverbakk** [comment]
@ymwdalex  Awesome, this did the trick. Thank you for your timeliness and creating this library!
