### ISSUE TITLE
Error installing sparse-dot-topn-for-blocks using pipx

### ISSUE THREAD

**Issue by audiomuze** [ing-bank/sparse_dot_topn#91]
Hi 

I'm running Python 3.11.5, pip 23.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11) and pipx 1.2.0 on Arch Linux 6.5.8-arch1-1

```pipx install sparse-dot-topn-for-blocks``` throws the following errors:

```
Fatal error from pip prevented installation. Full pip output in file:
    /home/x/.local/pipx/logs/cmd_2023-10-22_18.37.37_pip_errors.log

pip failed to build package:
    sparse-dot-topn-for-blocks

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers.pxd' not found
    sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers/ArrayWrapper_int.pxd' not found
    sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers/ArrayWrapper_float.pxd' not found
    sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers/ArrayWrapper_double.pxd' not found
    Cython.Compiler.Errors.CompileError: ./sparse_dot_topn_for_blocks/sparse_dot_topn.pyx

Error installing sparse-dot-topn-for-blocks.
```
Pastebin [here](https://pastebin.com/PsAcTidZ)

Any help/insights gratefully received.

**Comment by audiomuze** [comment]
@stephanecollot any chance you could take a look at resolving this to enable sparse_dot_topn to work with latest Cython?

**Comment by RUrlus** [comment]
@audiomuze this is not the right package/repo, the error is coming from `sparse_dot_topn_for_blocks` which forked off from this repo but is otherwise not related
