### ISSUE TITLE
Add wheels for python 3.12

### ISSUE THREAD

**Issue by mbaak** [ing-bank/sparse_dot_topn#92]
Hey, can you add wheels for python 3.12? Thanks!

**Comment by RUrlus** [comment]
3.12 requires a non-trivial change for the build system. 3.12 no longer contains distutils and current setup is deprecated.

**Comment by mbaak** [comment]
What is the plan?

**Comment by Fokko** [comment]
I would highly recommend using [ciwheelbuild](https://github.com/pypa/cibuildwheel) in the CI for building the wheels for the different versions/architectures. We use it over at PyIceberg, and it works very well 👍

**Comment by RUrlus** [comment]
@Fokko Thanks for the recommendation but we're already using cibuildwheel. The issue lies with the removal of `distutils` in 3.12 which we indirectly rely on. The solution is to switch to a more modern build system but I want to switch to nanobind for the bindings as well.

**Comment by mbaak** [comment]
@ymwdalex @stephanecollot @RUrlus So looks like we need to migrate for python 3.12. Let's discuss the plan of action? 
Perhaps also a good occasion to switch to pybind instead of cython, which should also make this easier to maintain in the future?

**Comment by RUrlus** [comment]
@ymwdalex @stephanecollot Given the many issues there have been with Cython, I am willing to pick this up but it will be part of a refactor where we switch bindings and drop some unused variants.

I am fairly sure that there is a segfault hidden in the threaded version that is masked by the (overly) large memory allocation. On that front I would suggest moving to OpenMP as this has become the defacto standard

**Comment by mbaak** [comment]
Without any comments I suggest we just pick this up @RUrlus.

**Comment by RUrlus** [comment]
@ymwdalex in the case of no feedback we will take over maintenance and start with the following changes:

1. Switch to Nanobind  for bindings with scikit-core build-system
2. Switch top OpenMP for threading

This will introduce breaking changes and we'll do a major release.

**Comment by ymwdalex** [comment]
@RUrlus @mbaak sorry for no response since you opened this issue. Both @stephanecollot and me have been quite busy in Nov and Dec and have no time to facilitate the improvement and new release.

Shall I add both of you as pypi project collaborator? so that you can do the release by yourselves.

**Comment by RUrlus** [comment]
@ymwdalex no worries. Yes please on PyPi. Can you also grant me admin rights for the repo? I can’t access many of the settings.

**Comment by ymwdalex** [comment]
@RUrlus could you please provide me your and @mbaak email? I can add you into Pypi.

For this repo, I am not admin neither. Could you please request admin right from the admin of https://github.com/ing-bank?

**Comment by RUrlus** [comment]
@ymwdalex 

> @RUrlus could you please provide me your and @mbaak email? I can add you into Pypi.
> 
> For this repo, I am not admin neither. Could you please request admin right from the admin of https://github.com/ing-bank?

I've send both are usernames and emails to your author email just now
