### ISSUE TITLE
Error: Maximum Recursion Depth Exceeded

### ISSUE THREAD

**Issue by ilalangapp** [ing-bank/sparse_dot_topn#96]
Hi, i just realised that you recently just did a migration.  I changed my usual function code from `awesome_cossim_topn` to `sp_matmul_topn` as explained. But I got an error result as follows:
`maximum recursion depth exceeded`

Any idea why and how to fix it, please? Thank you.

**Comment by RUrlus** [comment]
Ha @ilalangapp can you share the code how you import and call the function?
Because this is very unexpected and hard to replicate without a minimal reproducible example.

**Comment by RUrlus** [comment]
@ilalangapp I am closing the issue due to a lack of response. Please re-open the issue if it still relevant.
